In [4]:
import numpy as np
import open3d as o3d

data = np.load('/mnt/c/Classes/CIS4780/3D-Classification/Data/toys4k_point_clouds/chicken/chicken_000/pc10K.npz', allow_pickle=True)

data = data['dct']

data = data.item()

pc = data['pc']

pc = pc.tolist()

normal = data['normals']

normal = normal.tolist()

#print(data['normals'])

data = []

for i in range(0, len(pc)):
    l = []
    l.extend(pc[i])
    l.extend(normal[i])
    data.append(l)

data = np.array(data)

pcd = o3d.geometry.PointCloud()

pcd.points = o3d.utility.Vector3dVector(data[:, 0:3])

pcd.normals = o3d.utility.Vector3dVector(data[:, 3:6])

pcd.paint_uniform_color([0, 0, 0])

# Save data (if needed)
with open('chicken.xyzn', 'w') as f:
    for item in data:
        for vertex in item:
           f.write("%s, " % vertex)
        f.write("\n" % item)

# pcd = o3d.io.read_point_cloud('chicken.xyzn', format='xyzn')

print(pcd)

print(np.asarray(pcd.points))

o3d.visualization.draw_geometries([pcd])


# new_data = np.loadtxt('chicken.xyzn', delimiter=',')

#ply_point_cloud = o3d.data.PLYPointCloud()

# pcd = o3d.io.read_point_cloud(ply_point_cloud.path)
# print(pcd)
# print(np.asarray(pcd.points))

# o3d.visualization.draw_geometries([pcd],
#                                   zoom=0.3412,
#                                   front=[0.4257, -0.2125, -0.8795],
#                                   lookat=[2.6172, 2.0475, 1.532],
#                                   up=[-0.0694, -0.9768, 0.2024])

#normals = data['normals']

# o3d.io.write_point_cloud("chicken.ply", pcd)

#print(data)

PointCloud with 10000 points.
[[ 0.15847876  0.39886185 -0.1011014 ]
 [ 0.47132911 -0.28271183  0.28292813]
 [-0.12147371  0.27058881  0.61450626]
 ...
 [-0.18715949 -0.09785141 -0.57978405]
 [-0.28333744  0.18021312  0.11223037]
 [-0.07066383 -0.56003962 -0.02675571]]
